apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: acrworkflow1684159953872.azurecr.io/image-workflow-1684159953872:06e23a3ade45c782d3c8c0c472aa9bc9522ba01c
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: 20.251.113.103
  ports:
  - port: 80
  selector:
    app: nginx
